//! System tray icon + right-click menu via direct `Shell_NotifyIconW`.
//!
//! Runs in a dedicated std thread with a hidden message-only window.
//! User clicks are translated into [`TrayEvent`]s delivered through a
//! tokio mpsc so the main async loop can react alongside hotkey / core
//! events.
//!
//! Menu layout:
//!   * **Settings…**                  → [`TrayEvent::OpenSettings`]
//!   * **Microphone ▸**
//!       Auto (✓ when current)
//!       ── each cpal input device, ✓ on current selection ──
//!                                    → [`TrayEvent::SelectMicrophone`]
//!   * **Quit**                       → [`TrayEvent::Quit`]
//!
//! Icon is loaded from `airtalk/assets/tray_icon.rgba` (32×32 premultiplied
//! RGBA, generated by `tools/iconlab`). Swapped R↔B into a Windows DIB,
//! paired with an all-zero monochrome mask, fed into `CreateIconIndirect`.

#![cfg(windows)]

use std::ffi::c_void;
use std::sync::mpsc;
use std::sync::{Arc, Mutex, OnceLock};
use std::thread::JoinHandle;
use std::time::Duration;

use anyhow::{anyhow, bail, Context, Result};
use tokio::sync::mpsc as tokio_mpsc;
use windows::core::PCWSTR;
use windows::Win32::Foundation::{BOOL, HINSTANCE, HWND, LPARAM, LRESULT, POINT, WPARAM};
use windows::Win32::Graphics::Gdi::{
    CreateBitmap, CreateDIBSection, DeleteObject, BITMAPINFO, BITMAPINFOHEADER, BI_RGB,
    DIB_RGB_COLORS,
};
use windows::Win32::System::LibraryLoader::GetModuleHandleW;
use windows::Win32::UI::Shell::{
    Shell_NotifyIconW, NIF_ICON, NIF_MESSAGE, NIF_TIP, NIM_ADD, NIM_DELETE, NOTIFYICONDATAW,
};
use windows::Win32::UI::WindowsAndMessaging::{
    AppendMenuW, CreateIconIndirect, CreatePopupMenu, CreateWindowExW, DefWindowProcW, DestroyIcon,
    DestroyMenu, DestroyWindow, DispatchMessageW, GetCursorPos, GetMessageW, LoadCursorW,
    PostMessageW, PostQuitMessage, RegisterClassExW, SetForegroundWindow, TrackPopupMenu,
    TranslateMessage, CS_HREDRAW, CS_VREDRAW, HICON, HMENU, ICONINFO, IDC_ARROW, MF_CHECKED,
    MF_POPUP, MF_SEPARATOR, MF_STRING, MSG, TPM_BOTTOMALIGN, TPM_LEFTALIGN, TPM_RIGHTBUTTON,
    WM_APP, WM_COMMAND, WM_DESTROY, WM_LBUTTONDBLCLK, WM_RBUTTONUP, WNDCLASSEXW, WS_OVERLAPPED,
};

use crate::audio::{self, DeviceChoice};

// 32x32 premultiplied RGBA. Generated by tools/iconlab and committed.
const TRAY_ICON_RGBA: &[u8] = include_bytes!("../assets/tray_icon.rgba");
const TRAY_ICON_SIZE: i32 = 32;

/// Unique within airtalk — Shell_NotifyIcon uses this to identify our icon.
const TRAY_ICON_ID: u32 = 1;
/// Shell_NotifyIcon callback messages come in on this message number.
/// Must be in the WM_APP..0xBFFF range per MSDN.
const WM_TRAY_CALLBACK: u32 = WM_APP + 1;

const MENU_ID_SETTINGS: u32 = 1001;
const MENU_ID_QUIT: u32 = 1002;
/// "Auto" mic item. Device items use MENU_ID_MIC_BASE + index.
const MENU_ID_MIC_AUTO: u32 = 2000;
const MENU_ID_MIC_BASE: u32 = 2001;
const MENU_ID_MIC_MAX: u32 = 2999; // 999 devices is plenty

// ─── Public API ────────────────────────────────────────────────────────

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum TrayEvent {
    OpenSettings,
    Quit,
    /// User selected a microphone from the submenu. `DeviceChoice::Auto`
    /// follows the system default; `Named(_)` pins a specific device.
    SelectMicrophone(DeviceChoice),
}

pub struct Tray {
    events: tokio_mpsc::UnboundedReceiver<TrayEvent>,
    _thread: JoinHandle<()>,
}

impl Tray {
    pub fn start(initial_mic: DeviceChoice) -> Result<Self> {
        let (event_tx, event_rx) = tokio_mpsc::unbounded_channel();
        EVENT_TX
            .set(event_tx)
            .map_err(|_| anyhow!("Tray::start already called in this process"))?;
        CURRENT_MIC
            .set(Mutex::new(initial_mic))
            .map_err(|_| anyhow!("Tray current mic already set"))?;
        let _ = LAST_MIC_LIST.set(Mutex::new(Vec::new()));

        let (init_tx, init_rx) = mpsc::channel::<Result<()>>();
        let thread = std::thread::Builder::new()
            .name("airtalk-tray".into())
            .spawn(move || {
                if let Err(e) = run_tray_thread(&init_tx) {
                    let _ = init_tx.send(Err(e));
                }
            })
            .context("spawn tray thread")?;

        init_rx
            .recv_timeout(Duration::from_secs(2))
            .context("tray init timeout (2s)")?
            .context("tray init error")?;

        Ok(Self {
            events: event_rx,
            _thread: thread,
        })
    }

    pub async fn recv(&mut self) -> Option<TrayEvent> {
        self.events.recv().await
    }

    /// Update the tray's idea of the current mic so the next menu render
    /// shows the right checkmark. Called by main after a switch_to lands.
    pub fn set_current_mic(&self, choice: DeviceChoice) {
        if let Some(cell) = CURRENT_MIC.get() {
            if let Ok(mut guard) = cell.lock() {
                *guard = choice;
            }
        }
    }
}

// ─── Shared state ──────────────────────────────────────────────────────

static EVENT_TX: OnceLock<tokio_mpsc::UnboundedSender<TrayEvent>> = OnceLock::new();
static CURRENT_MIC: OnceLock<Mutex<DeviceChoice>> = OnceLock::new();
/// Snapshot of the device list shown in the most recent mic submenu —
/// so when a WM_COMMAND fires with MENU_ID_MIC_BASE + i, we can look up
/// which device name `i` refers to.
static LAST_MIC_LIST: OnceLock<Mutex<Vec<String>>> = OnceLock::new();

// ─── Thread entry ──────────────────────────────────────────────────────

fn run_tray_thread(init_tx: &mpsc::Sender<Result<()>>) -> Result<()> {
    unsafe {
        let h_instance = GetModuleHandleW(None).context("GetModuleHandleW")?;
        register_window_class(h_instance.into())?;
        let hwnd = create_message_window(h_instance.into())?;

        let icon = load_tray_icon().context("load tray icon")?;

        let mut nid: NOTIFYICONDATAW = std::mem::zeroed();
        nid.cbSize = std::mem::size_of::<NOTIFYICONDATAW>() as u32;
        nid.hWnd = hwnd;
        nid.uID = TRAY_ICON_ID;
        nid.uFlags = NIF_ICON | NIF_MESSAGE | NIF_TIP;
        nid.uCallbackMessage = WM_TRAY_CALLBACK;
        nid.hIcon = icon;
        let tip: Vec<u16> = "空·谈\0".encode_utf16().collect();
        let max = nid.szTip.len().min(tip.len());
        nid.szTip[..max].copy_from_slice(&tip[..max]);

        if !Shell_NotifyIconW(NIM_ADD, &nid).as_bool() {
            let _ = DestroyIcon(icon);
            bail!("Shell_NotifyIconW(NIM_ADD) failed");
        }

        let _ = init_tx.send(Ok(()));

        let mut msg: MSG = std::mem::zeroed();
        loop {
            let ret = GetMessageW(&mut msg, None, 0, 0);
            if ret.0 <= 0 {
                break;
            }
            let _ = TranslateMessage(&msg);
            DispatchMessageW(&msg);
        }

        let mut del: NOTIFYICONDATAW = std::mem::zeroed();
        del.cbSize = std::mem::size_of::<NOTIFYICONDATAW>() as u32;
        del.hWnd = hwnd;
        del.uID = TRAY_ICON_ID;
        let _ = Shell_NotifyIconW(NIM_DELETE, &del);
        let _ = DestroyIcon(icon);
        let _ = DestroyWindow(hwnd);
    }
    Ok(())
}

// ─── Icon loading ──────────────────────────────────────────────────────

unsafe fn load_tray_icon() -> Result<HICON> {
    let expected = (TRAY_ICON_SIZE * TRAY_ICON_SIZE * 4) as usize;
    if TRAY_ICON_RGBA.len() != expected {
        bail!(
            "tray_icon.rgba is {} bytes, expected {} (regenerate with `uv run iconlab`)",
            TRAY_ICON_RGBA.len(),
            expected
        );
    }

    let mut bgra = Vec::with_capacity(TRAY_ICON_RGBA.len());
    for chunk in TRAY_ICON_RGBA.chunks(4) {
        bgra.push(chunk[2]); // B
        bgra.push(chunk[1]); // G
        bgra.push(chunk[0]); // R
        bgra.push(chunk[3]); // A
    }

    let bi = BITMAPINFO {
        bmiHeader: BITMAPINFOHEADER {
            biSize: std::mem::size_of::<BITMAPINFOHEADER>() as u32,
            biWidth: TRAY_ICON_SIZE,
            biHeight: -TRAY_ICON_SIZE,
            biPlanes: 1,
            biBitCount: 32,
            biCompression: BI_RGB.0,
            biSizeImage: 0,
            biXPelsPerMeter: 0,
            biYPelsPerMeter: 0,
            biClrUsed: 0,
            biClrImportant: 0,
        },
        bmiColors: [Default::default(); 1],
    };
    let mut bits: *mut c_void = std::ptr::null_mut();
    let color_dib = CreateDIBSection(None, &bi, DIB_RGB_COLORS, &mut bits, None, 0)
        .context("CreateDIBSection")?;
    if bits.is_null() {
        let _ = DeleteObject(color_dib.into());
        bail!("CreateDIBSection returned null bits");
    }
    std::ptr::copy_nonoverlapping(bgra.as_ptr(), bits as *mut u8, bgra.len());

    let mask_bytes = vec![0u8; ((TRAY_ICON_SIZE * TRAY_ICON_SIZE) as usize).div_ceil(8)];
    let mask = CreateBitmap(
        TRAY_ICON_SIZE,
        TRAY_ICON_SIZE,
        1,
        1,
        Some(mask_bytes.as_ptr() as *const _),
    );
    if mask.is_invalid() {
        let _ = DeleteObject(color_dib.into());
        bail!("CreateBitmap(mask) failed");
    }

    let info = ICONINFO {
        fIcon: BOOL(1),
        xHotspot: 0,
        yHotspot: 0,
        hbmMask: mask,
        hbmColor: color_dib,
    };
    let icon = CreateIconIndirect(&info).context("CreateIconIndirect")?;
    let _ = DeleteObject(color_dib.into());
    let _ = DeleteObject(mask.into());
    Ok(icon)
}

// ─── Window class + window ─────────────────────────────────────────────

unsafe fn register_window_class(h_instance: HINSTANCE) -> Result<()> {
    let class_name: Vec<u16> = "airtalkTray\0".encode_utf16().collect();
    let wnd_class = WNDCLASSEXW {
        cbSize: std::mem::size_of::<WNDCLASSEXW>() as u32,
        style: CS_HREDRAW | CS_VREDRAW,
        lpfnWndProc: Some(wnd_proc),
        cbClsExtra: 0,
        cbWndExtra: 0,
        hInstance: h_instance,
        hIcon: Default::default(),
        hCursor: LoadCursorW(None, IDC_ARROW).unwrap_or_default(),
        hbrBackground: Default::default(),
        lpszMenuName: PCWSTR::null(),
        lpszClassName: PCWSTR(class_name.as_ptr()),
        hIconSm: Default::default(),
    };
    let atom = RegisterClassExW(&wnd_class);
    if atom == 0 {
        let err = windows::Win32::Foundation::GetLastError();
        if err.0 != 1410 {
            bail!("RegisterClassExW(airtalkTray) failed: {err:?}");
        }
    }
    Ok(())
}

unsafe fn create_message_window(h_instance: HINSTANCE) -> Result<HWND> {
    let class_name: Vec<u16> = "airtalkTray\0".encode_utf16().collect();
    let window_name: Vec<u16> = "airtalk-tray\0".encode_utf16().collect();
    let hwnd = CreateWindowExW(
        Default::default(),
        PCWSTR(class_name.as_ptr()),
        PCWSTR(window_name.as_ptr()),
        WS_OVERLAPPED,
        0,
        0,
        0,
        0,
        None,
        None,
        Some(h_instance),
        None,
    )
    .context("CreateWindowExW(tray)")?;
    Ok(hwnd)
}

// ─── Window procedure ──────────────────────────────────────────────────

unsafe extern "system" fn wnd_proc(
    hwnd: HWND,
    msg: u32,
    w_param: WPARAM,
    l_param: LPARAM,
) -> LRESULT {
    match msg {
        WM_TRAY_CALLBACK => {
            let mouse_msg = (l_param.0 as u32) & 0xFFFF;
            match mouse_msg {
                WM_RBUTTONUP => show_context_menu(hwnd),
                WM_LBUTTONDBLCLK => emit(TrayEvent::OpenSettings),
                _ => {}
            }
            LRESULT(0)
        }
        WM_COMMAND => {
            let id = (w_param.0 as u32) & 0xFFFF;
            handle_menu_command(id);
            LRESULT(0)
        }
        WM_DESTROY => {
            PostQuitMessage(0);
            LRESULT(0)
        }
        _ => DefWindowProcW(hwnd, msg, w_param, l_param),
    }
}

fn handle_menu_command(id: u32) {
    match id {
        MENU_ID_SETTINGS => emit(TrayEvent::OpenSettings),
        MENU_ID_QUIT => emit(TrayEvent::Quit),
        MENU_ID_MIC_AUTO => emit(TrayEvent::SelectMicrophone(DeviceChoice::Auto)),
        id if (MENU_ID_MIC_BASE..=MENU_ID_MIC_MAX).contains(&id) => {
            let idx = (id - MENU_ID_MIC_BASE) as usize;
            if let Some(list) = LAST_MIC_LIST.get() {
                if let Ok(guard) = list.lock() {
                    if let Some(name) = guard.get(idx) {
                        emit(TrayEvent::SelectMicrophone(DeviceChoice::Named(
                            name.clone(),
                        )));
                    }
                }
            }
        }
        _ => {}
    }
}

// ─── Menu building ─────────────────────────────────────────────────────

unsafe fn show_context_menu(hwnd: HWND) {
    let menu = match CreatePopupMenu() {
        Ok(m) => m,
        Err(_) => return,
    };

    append_item(menu, MENU_ID_SETTINGS, "Settings…");

    let mic_submenu = build_mic_submenu();
    if let Some(sub) = mic_submenu {
        let label: Vec<u16> = "Microphone\0".encode_utf16().collect();
        let _ = AppendMenuW(menu, MF_POPUP, sub.0 as usize, PCWSTR(label.as_ptr()));
    }

    let _ = AppendMenuW(menu, MF_SEPARATOR, 0, PCWSTR::null());
    append_item(menu, MENU_ID_QUIT, "Quit airtalk");

    let mut pt = POINT { x: 0, y: 0 };
    let _ = GetCursorPos(&mut pt);
    let _ = SetForegroundWindow(hwnd);

    let _ = TrackPopupMenu(
        menu,
        TPM_RIGHTBUTTON | TPM_LEFTALIGN | TPM_BOTTOMALIGN,
        pt.x,
        pt.y,
        Some(0),
        hwnd,
        None,
    );
    let _ = PostMessageW(Some(hwnd), WM_COMMAND, WPARAM(0), LPARAM(0));

    let _ = DestroyMenu(menu);
}

/// Build a popup menu of input devices. Returns Some(HMENU) on success —
/// the caller owns it and must pass it to `AppendMenuW(MF_POPUP, …)`,
/// which transfers ownership to the parent menu (no explicit DestroyMenu
/// needed for submenus).
unsafe fn build_mic_submenu() -> Option<HMENU> {
    let sub = CreatePopupMenu().ok()?;

    let current = CURRENT_MIC
        .get()
        .and_then(|m| m.lock().ok())
        .map(|g| g.clone())
        .unwrap_or(DeviceChoice::Auto);

    let devices = audio::list_input_devices();

    // Remember this exact list so WM_COMMAND can map index → name.
    if let Some(cell) = LAST_MIC_LIST.get() {
        if let Ok(mut guard) = cell.lock() {
            *guard = devices.clone();
        }
    }

    // Auto row.
    let auto_checked = matches!(current, DeviceChoice::Auto);
    append_checkable(sub, MENU_ID_MIC_AUTO, "Auto (system default)", auto_checked);

    if !devices.is_empty() {
        let _ = AppendMenuW(sub, MF_SEPARATOR, 0, PCWSTR::null());
    }

    for (i, name) in devices.iter().enumerate() {
        if i as u32 > MENU_ID_MIC_MAX - MENU_ID_MIC_BASE {
            break;
        }
        let id = MENU_ID_MIC_BASE + i as u32;
        let checked = matches!(&current, DeviceChoice::Named(n) if n == name);
        append_checkable(sub, id, name, checked);
    }

    Some(sub)
}

unsafe fn append_item(menu: HMENU, id: u32, label: &str) {
    let wide: Vec<u16> = label.encode_utf16().chain(std::iter::once(0)).collect();
    let _ = AppendMenuW(menu, MF_STRING, id as usize, PCWSTR(wide.as_ptr()));
}

unsafe fn append_checkable(menu: HMENU, id: u32, label: &str, checked: bool) {
    let wide: Vec<u16> = label.encode_utf16().chain(std::iter::once(0)).collect();
    let flags = if checked {
        MF_STRING | MF_CHECKED
    } else {
        MF_STRING
    };
    let _ = AppendMenuW(menu, flags, id as usize, PCWSTR(wide.as_ptr()));
}

fn emit(event: TrayEvent) {
    if let Some(tx) = EVENT_TX.get() {
        let _ = tx.send(event);
    }
}

// Quiet a warning on the unused Arc import since Mutex is from std::sync
#[allow(dead_code)]
fn _arc_marker() -> Arc<()> {
    Arc::new(())
}
